# ruff: noqa
# fmt: off
# Generated by Django 4.2.16; kept explicit so planner evidence is reviewable.

import career_codesk.domain
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("planning", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PlannerRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=career_codesk.domain.domain_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("schema_version", models.CharField(default="1.0", max_length=32)),
                ("fixture_scope", models.CharField(default="synthetic-demo-v1", max_length=64)),
                ("input_digest", models.CharField(db_index=True, max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("algorithm_version", models.CharField(max_length=64)),
                ("seed_metadata", models.JSONField(default=dict)),
                ("source_ids", models.JSONField(default=list)),
                ("canonical_input", models.JSONField()),
                ("canonical_result", models.JSONField()),
                ("result_digest", models.CharField(db_index=True, max_length=64)),
            ],
        )
    ]
